import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';
import { useEffect } from 'react';
import { Lexer } from '../language/lexer';
import { input } from '../language/input';
import { TokenType } from '../language/token';
import { parser } from '../language/parser';
import { evaluate } from '../language/evaluate';
import { Environment } from '../language/object';

const Editor = dynamic(import('../compontents/Editor'), { ssr: false })

const Home: NextPage = () => {

  useEffect(() => {
    const lexer = new Lexer(input);
    // const test = new Lexer(input);
    // let a = test.lexer();
    // while(a.TokenType !== TokenType.EOF){
    //   console.log(a)
    //   a = test.lexer();
    // }
    const parse = new parser(lexer);
    const Program = parse.Program();
    console.log(Program);
    evaluate(Program,new Environment());
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Editor />
      


    </div>
  )
}

export default Home
