import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';

const Editor = dynamic(import('../compontents/Editor'), { ssr: false })

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Editor />



    </div>
  )
}

export default Home
